name        = "borshevik-installer"
description = "Borshevik installer ISO"
version     = "42"
distro      = "fedora-42"      # берём правильный Fedora-42 деф

[customizations.ostree]
url = "registry:ghcr.io/komorebinator/borshevik:latest"
ref = "borshevik"

[customizations.installer.kickstart]
contents = """
clearpart --all --initlabel
autopart --type=lvm --fstype=ext4

%post
bootc switch --mutate-in-place --transport ostree ref=borshevik
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage"
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Subscription",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]
