name        = "borshevik-installer-nvidia"
description = "Borshevik installer (nvidia)"
version     = "42"
distro      = "fedora-42"

[customizations.ostree]
url = "registry:ghcr.io/komorebinator/borshevik-nvidia:latest"
ref = "borshevik-nvidia"

[customizations.installer.kickstart]
contents = """
clearpart --all --initlabel
autopart --type=lvm --fstype=ext4

%post
bootc switch --mutate-in-place --transport ostree ref=borshevik-nvidia
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage"
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Subscription",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]
